package config

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

type NetworkPolicy struct {
	Name      string     `yaml:"name"`
	Endpoints []Endpoint `yaml:"endpoints"`
	Binaries  []Binary   `yaml:"binaries"`
}

type Policy struct {
	Version          int                      `yaml:"version"`
	FilesystemPolicy FilesystemPolicy         `yaml:"filesystem_policy"`
	Landlock         LandlockConfig           `yaml:"landlock"`
	Process          ProcessConfig            `yaml:"process"`
	NetworkPolicies  map[string]NetworkPolicy `yaml:"network_policies"`
}

type FilesystemPolicy struct {
	IncludeWorkDir bool     `yaml:"include_workdir"`
	ReadOnly       []string `yaml:"read_only"`
	ReadWrite      []string `yaml:"read_write"`
}

type LandlockConfig struct {
	Compatibility string `yaml:"compatibility"`
}

type ProcessConfig struct {
	RunAsUser  string `yaml:"run_as_user"`
	RunAsGroup string `yaml:"run_as_group"`
}

func GeneratePolicy(cfg *Config) *Policy {
	policy := &Policy{
		Version: 1,
		FilesystemPolicy: FilesystemPolicy{
			IncludeWorkDir: true,
			ReadOnly: []string{
				"/usr", "/lib", "/proc", "/dev/urandom", "/app",
				"/etc", "/var/log", "/etc/ssl", "/etc/ca-certificates",
			},
			ReadWrite: []string{"/sandbox", "/tmp", "/dev/null"},
		},
		Landlock:        LandlockConfig{Compatibility: "best_effort"},
		Process:         ProcessConfig{RunAsUser: "sandbox", RunAsGroup: "sandbox"},
		NetworkPolicies: make(map[string]NetworkPolicy),
	}

	// APT policies
	if cfg.APT.Enable {
		if cfg.APT.Update {
			policy.FilesystemPolicy.ReadWrite = append(policy.FilesystemPolicy.ReadWrite,
				"/var/lib/apt/lists")
		}
		if cfg.APT.Install {
			policy.FilesystemPolicy.ReadWrite = append(policy.FilesystemPolicy.ReadWrite,
				"/var/lib/apt", "/var/cache/apt")
			policy.NetworkPolicies["apt_get"] = NetworkPolicy{
				Name: "APT Package Manager",
				Endpoints: []Endpoint{
					{Host: "archive.ubuntu.com", Port: 443, TLS: "skip"},
					{Host: "security.ubuntu.com", Port: 443, TLS: "skip"},
				},
				Binaries: []Binary{
					{Path: "/usr/bin/apt"},
					{Path: "/usr/bin/apt-get"},
				},
			}
		}
	}

	// Git policies
	if cfg.Git.Enable {
		if cfg.Git.Read {
			policy.NetworkPolicies["git_pull"] = NetworkPolicy{
				Name: "Git Pull",
				Endpoints: []Endpoint{
					{Host: cfg.Git.Endpoint, Port: 443, TLS: "skip"},
				},
				Binaries: []Binary{{Path: "/usr/bin/git"}},
			}
		}
		if cfg.Git.Write {
			policy.NetworkPolicies["git_push"] = NetworkPolicy{
				Name: "Git Push",
				Endpoints: []Endpoint{
					{Host: cfg.Git.Endpoint, Port: 443, TLS: "skip"},
				},
				Binaries: []Binary{{Path: "/usr/bin/git"}},
			}
		}
	}

	// Websearch policy
	if cfg.Websearch {
		policy.NetworkPolicies["exa_ai"] = NetworkPolicy{
			Name: "Exa AI Search",
			Endpoints: []Endpoint{
				{Host: "api.exa.ai", Port: 443, TLS: "skip"},
			},
			Binaries: []Binary{{Path: "/usr/bin/curl"}},
		}
	}

	// NPM policies
	if cfg.NPM.Enable {
		endpoints := []Endpoint{
			{Host: "registry.npmjs.org", Port: 443, TLS: "skip"},
			{Host: "api.npmjs.org", Port: 443, TLS: "skip"},
		}
		binaries := []Binary{}

		if cfg.NPM.Install {
			binaries = append(binaries, Binary{Path: "/usr/bin/npm"})
		}
		if cfg.NPM.Execute {
			binaries = append(binaries, Binary{Path: "/usr/bin/npx"}, Binary{Path: "/usr/bin/node"})
		}

		if len(binaries) > 0 {
			policy.NetworkPolicies["npm_registry"] = NetworkPolicy{
				Name:      "npm Registry",
				Endpoints: endpoints,
				Binaries:  binaries,
			}
		}
	}

	return policy
}

func (p *Policy) Save(path string) error {
	os.MkdirAll(filepath.Dir(path), 0755)

	data, err := yaml.Marshal(p)
	if err != nil {
		return fmt.Errorf("marshal policy: %w", err)
	}

	header := fmt.Sprintf("# OpenShell Policy - Generated by ospm\n# DO NOT EDIT MANUALLY\n---\n")

	return os.WriteFile(path, []byte(header+string(data)), 0644)
}
